### PR TITLE
Fix file paths

### PR DESCRIPTION
**Pull request by naomiajacobs**

### CODE REVIEW

**Comment by naomiajacobs** [comment]
@juanca can you take a look please?

**Comment by naomiajacobs** [comment]
@lambdatastic can you take a look at this?

**Comment by juanca** [comment]
This shouldn't be a problem if we're exporting a bundled file. Can we verify?

**Comment by naomiajacobs** [comment]
@juanca yes ideally we would be but right now we're not - can we merge this in now and fix later so that it's not blocking snowpeople?

**Comment by juanca** [comment]
I'm fine with that. Let's try to dedicate a 1 point story in verifying a correct bundle. I'm on mobile but I can green light this soon

**Comment by naomiajacobs** [comment]
@juanca we should be but I think we are not - can we get this in now to unblock snowpeople and fix it later?

**Pull request merged**
